<a href="https://colab.research.google.com/github/victorlee0923-creator/ML_Book_Examples/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.36377297, 0.38183142, 0.33295081, 0.64885793],
       [0.28803206, 0.36081766, 0.71882209, 0.52712746],
       [0.22478147, 0.2031117 , 0.51820891, 0.36996993]])

In [4]:
np1.dtype


dtype('float64')

# **TENSORS**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.7267, -1.1941,  1.3018, -1.1775],
        [ 0.0043, -0.6865,  0.9996, -1.5672],
        [ 1.0862,  1.3208, -2.3224,  0.2362]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5179, 0.0694, 0.5080, 0.2110],
        [0.2858, 0.7480, 0.6428, 0.8311],
        [0.0631, 0.5618, 0.0283, 0.2027]], dtype=torch.float64)