# Ch 0. Python與機器學習
## 0-4. 基礎數學與Python實作
[0-4-1. 基本操作](#sec1)  
***

<a id='sec1'></a>
## 0-4-1. 基本操作

In [1]:
# 向量也可以用串列來實作
A = [1, 2, 3]
B = [4, 5, 6]

def 向量相加(a, b):
    return [a_i+b_i for a_i, b_i in zip(a, b)]

def 向量內積(a, b):
    return sum(a_i*b_i for a_i, b_i in zip(a, b))

print(向量相加(A, B))
print(向量內積(A, B))

[5, 7, 9]
32


In [2]:
# 向量建議用 numpy 的陣列來實作
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('向量相加：', A+B)
print('純量、向量相乘：', 3*A)
print('向量相乘：', A*B)
print('向量內積：', np.dot(A, B))
print('向量長度：', np.linalg.norm(A))

向量相加： [5 7 9]
純量、向量相乘： [3 6 9]
向量相乘： [ 4 10 18]
向量內積： 32
向量長度： 3.7416573867739413


Numpy 提供的多維度陣列 ndarray，有三個主要屬性：
- 維度(ndim)
- 形狀(shape)
- 數值型態(dtype)：預設的整數型態是 int32，浮點數為 float64

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.ndim)
print(arr.shape) # 常用
print(arr.dtype)

1
(6,)
int32


In [4]:
# 兩種改變陣列的形狀與維度的方法
arr.shape = 2, 3
print(arr)
arr1 = arr.reshape(3, 2)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


事實上，numpy 有矩陣的資料結構，但官網[NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)建議採用 ndarray，原因有：
1. 是 numpy 的標準資料結構，且許多 numpy 函式回傳的是 ndarray 而非 matrix
2. 能進行元素的運算，與線性代數運算時使用的運算符號有明顯區隔

In [5]:
matrix = np.mat([[1, 2, 3], [4, 5, 6]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# 矩陣相乘
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0, 0], [0, 1, 1], [1, 0, 1]])
print(np.dot(A, B))     # 矩陣相乘
print(A.transpose())    # 矩陣轉置，也可用 A.T
print(np.linalg.inv(B)) # 反矩陣

[[ 4  2  5]
 [10  5 11]]
[[1 4]
 [2 5]
 [3 6]]
[[ 1.  0.  0.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


In [7]:
# 注意 1：若矩陣為不可逆(singular)將沒有反矩陣，建議用下列寫法
try:
    inv = np.linalg.inv(B)
except np.linalg.LinAlgError:
    print('不可逆矩陣')

In [8]:
# 注意 2：轉置對一維陣列沒用
arr = np.array([1, 2, 3]) # 一維陣列
print(arr.transpose())
arr = np.array([[1, 2, 3]]) # 二維陣列
print(arr.transpose())

[1 2 3]
[[1]
 [2]
 [3]]


In [9]:
# 攤平矩陣
A = np.array([[1, 2, 3], [4, 5, 6]])
A.flatten()  # 得到一維陣列

array([1, 2, 3, 4, 5, 6])

In [10]:
# 得到二維陣列 1×6 (常用)，-1 代表自動使用所需的最大值
A.reshape(1, -1) 

array([[1, 2, 3, 4, 5, 6]])

In [11]:
# 找最大最小值、平均值、變異數、標準差
print(np.min(A))
print(np.max(A))
print(np.mean(A))
print(np.var(A))
print(np.std(A))

1
6
3.5
2.9166666666666665
1.707825127659933


線性代數的基礎計算

In [12]:
# 矩陣的秩(rank)
mat = np.array([[1, 2, 3], [0, 2, 2], [1, 4, 5]])
np.linalg.matrix_rank(mat)

2

In [13]:
# 矩陣的行列式
np.linalg.det(mat)

0.0

In [14]:
# 取得矩陣的對角線元素
mat.diagonal()

array([1, 2, 5])

In [15]:
# 特徵值(eigenvalue)與特徵向量(eigenvector)
egn_val, egn_vec = np.linalg.eig(mat)
print(egn_val)
print(egn_vec)

[7.16227766e+00 8.37722340e-01 6.69288394e-17]
[[ 0.49599178  0.80711093 -0.57735027]
 [ 0.31369274 -0.51046177 -0.57735027]
 [ 0.80968452  0.29664916  0.57735027]]
